CREATE TABLE bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(2048) NOT NULL,
    title VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_bookmarks_url UNIQUE (url)
);

CREATE TABLE bookmark_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookmark_id BIGINT NOT NULL,
    tag_value VARCHAR(255) NOT NULL,
    CONSTRAINT fk_bookmark_tags_bookmark FOREIGN KEY (bookmark_id) REFERENCES bookmarks (id) ON DELETE CASCADE,
    CONSTRAINT uk_bookmark_tags_bookmark_tag UNIQUE (bookmark_id, tag_value)
);
